Provide option to set sapadm and sidadm passwords
SUSE/sapnwbootstrap-formula pull request #19
Opened 2019-11-19 22:41 UTC by Simranpal

This PR provides the option to set individual sapadm and sidadm passwords for each NW instance, having the Master password as default. The idea is to provide the same level of configuration a user can modify from the SAP GUI installer.

2019-11-19 23:28 UTC, Simranpal commented
Need to identify the other areas, where the `sapadm` and `<sid>adm` passwords could replace the master password, such as enabling HA, sapservices, start/stop NW instances using the sapcontrol would require the `<sid>adm` password

2019-11-27 08:12 UTC, arbulu89 requested changes
@Simranpal Some comments.
- I guess that you confirmed that the same passwords usage in all hosts is the way to go. If this is the case perfect, otherwise, we need to provide to set individual passwords.
- I don't find the changes in the templates for `ascs`. `pas` and `aas` and they should have the same parameter. Maybe we need to update the template to add this option. Otherwise it doesn't have sense to pass the values.
- Maybe we could improve the next line that is repeated many times:
`netweaver.sap_adm_password|default(netweaver.master_password)`
and put it in other place (`defaults`, `map.jinja`), just to do it once. What do you think?

2019-11-27 08:12 UTC, arbulu89 commented on netweaver/install_ascs.sls
> +    - password: {{ netweaver.master_password }}
Is this the `master_password` or the `sidadm` password? I would say the 2nd, but I'm not sure

2019-11-27 08:12 UTC, arbulu89 commented on netweaver/install_ascs.sls
> +    - password: {{ netweaver.master_password }}
The same for the other sap instances

2019-11-29 00:42 UTC, Simranpal commented
> @Simranpal Some comments.
> 
> * I guess that you confirmed that the same passwords usage in all hosts is the way to go. If this is the case perfect, otherwise, we need to provide to set individual passwords.

That's what I have found so far from documentation and search.

> * I don't find the changes in the templates for `ascs`. `pas` and `aas` and they should have the same parameter. Maybe we need to update the template to add this option. Otherwise it doesn't have sense to pass the values.

I noticed that those passwords in those instances templates were commented out. Maybe you changed it or was there when you copied the template?
I can add the interpolation for relevant passwords in those templates as well.

> * Maybe we could improve the next line that is repeated many times:
>   `netweaver.sap_adm_password|default(netweaver.master_password)`
>   and put it in other place (`defaults`, `map.jinja`), just to do it once. What do you think?

That would be good, but for 
1. adding this line in defaults.yaml, I would have to import the password pillar info there which doesnt make sense.
2. I guess you mean adding something like `{% set instance_password = netweaver.sap_adm_password|default(netweaver.master_password) %}
` to map.jinja which would mean importing  this instance_password.
3. Setting this variable in each file 
Is there other efficient way you think?

2019-11-29 07:58 UTC, arbulu89 commented
Hey @Simranpal ,

> I noticed that those passwords in those instances templates were commented out. Maybe you changed it or was there when you copied the template?
I can add the interpolation for relevant passwords in those templates as well.

I used the templates that are created by the manual execution, so I guess that the `sapinst` tool itself doesn't uncomment this lines if the passwords are the same, but we have to. The passwords must be applied to all instances, so if don't change the template, it won't, right?

About the default password thing, I don't have the answer, I wanted to make you research for a cleaner solution hehe I have not spent time looking options. For me, it it was possible, trying to eliminate these duplicates would make sense.

But this is just an improvement, as far as the logic works, and the passwords are applied as expected I don't really care, we can work on that in a future PR too.

Don't take every suggestion I do like a a `must` hehe There are just observations.

2019-12-05 11:19 UTC, arbulu89 approved these changes
@Simranpal Looks good!
Just a single comment added.
*Upgrade the package version changing `spec` and `changes` file.
Then it's ready to merge

2019-12-05 11:19 UTC, arbulu89 commented on netweaver/install_ers.sls
> +    - ascs_password: {{ netweaver.master_password }}
Shouldn't this be `{{ netweaver.sid_adm_password|default(netweaver.master_password) }}` ?

2019-12-09 19:03 UTC, merged