Update cluster properties in the template
SUSE/sapnwbootstrap-formula pull request #60
Opened 2020-09-14 23:18 UTC by Simranpal

Some changes to the cluster properties w.r.t Suse best practise guide as suggested by Peter Schinagl.

- Move properties `cib-bootstrap-options` ,` rsc_defaults` , `op_defaults` to general instead of AWS specific
- Change to `op monitor interval=11` for ASCS, ERS primitive
- Remove ERS meta resource stickiness

https://documentation.suse.com/sbp/all/single-html/SAP_NW740_SLE15_SetupGuide/

2020-09-15 07:01 UTC, arbulu89 reviewed
@Simranpal Thank you for the first implementation. I still have doubts if these values are correct for all the providers or not. This is something we need to know beforehand.

2020-09-15 07:02 UTC, arbulu89 commented
Adding @petersatsuse to the PR too

2020-10-12 07:45 UTC, MalloZup requested changes
this can wait SUMA MU .

after https://github.com/SUSE/spacewalk/issues/12421#issuecomment-706292904

2022-08-12 07:30 UTC, yeoldegrove commented
outdated by now

2022-08-12 07:30 UTC, closed without merging